### ISSUE TITLE
Refactor code - make package from core algorithm

### ISSUE THREAD

**Issue by RomanJuranek** [5G-ERA/CollisionWarningService#6]
Currently everything is just a bunch of python files - make a nice package which can be easily imported from other code.

Something like
```python
from fcw_core import ForwardCollisionGuard
guard = ForwardCollisionGuard.from_dict(config)
# ...
```

**Comment by RomanJuranek** [comment]
@klepo  It is not a good idea to extend `YOLODetector` (as done in 897e1b0ddb95880d879c7a5597c92793ae135de8). The detector should stay functional *without* 5g-era stuff. Rather implement a wrapper which initialize new detector inside another class instance. The idea is:
* Core package should be working without 5g-era packages
* Wrapper should use core functionality to implement client and interface

**Comment by klepo** [comment]
Fixed in 872153b.

**Comment by RomanJuranek** [comment]
I think this should not be closed yet. We need to restructure the directories in the repo and change the code accordingly. The code should not be in the root and we should also separate core/cloud/robot code.

* `collision_warning` - The core algorithm - roughly the modules `collision`, `detection`, `geometry`, `sort`, `yolo_detector`
* `collision_warning_service` - cloud code
* `collision_warning_client` - robot code

Not sure about the naming.

**Comment by klepo** [comment]
OK, let's define the code structure.
